application: simonowendesign
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "7d"

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /styles/css
  static_dir: /styles/css

- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico