application: simonowendesign
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "7d"

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /style\.css
  static_files: styles/css/style.css
  upload: styles/css/style\.css

- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico